data:
  train_urls:
      - "gs://levanter-eu/lakh-data-inter-16384/train.txt"
  validation_urls:
      - "gs://levanter-eu/lakh-data-inter-16384/valid.txt"
  cache_dir: "gs://levanter-eu/lakh-data-inter-16384/cache/"
  tokenizer: "passthrough"
  plaintext: True
  enforce_eos: False
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 16384
  scale_attn_by_inverse_layer_idx: true
  gradient_checkpointing: true
  embed_pdrop: 0.1
  resid_pdrop: 0.1
trainer:
  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 1
  num_train_steps: 115000
  #load_checkpoint_path: "gs://levanter-eu/lakh-checkpoints/blooming-plasma-85/step-104050"
  train_batch_size: 8

  checkpointer:
    base_path: gs://levanter-eu/lakh-checkpoints/
    save_interval: 30m

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  parameter_axis_resources:
    embed: "data"
optimizer:
  learning_rate: 6E-4
  weight_decay: 0.1
